-- MYSQL

TABLE PRODUCTS {
  ID INT PRIMARY KEY NOT NULL
  NAME VARCHAR(100)
  SLOGAN VARCHAR(100)
  DESCRIPTION VARCHAR(100)
  CATEGORY VARCHAR(100)
  DEFAULTPRICE VARCHAR(100)
  FOREIGN KEY PRODID
  FOREIGN KEY FEATURESID
}

TABLE STYLES {
  STYLEID INT PRIMARY KEY NOT NULL
  NAME VARCHAR(100)
  ORIGINALPRICE VARCHAR(5)
  SALEPRICE VARCHAR(5)
  DEFAULT BOOLEAN
  FOREIGN KEY PHOTOID
  FOREIGN KEY SKUID
}

TABLE RELATEDPRODUCTS {
  ID PRIMARY KEY INT NOT NULL AUTO INCREMENT
  PRODID
  RELATEDPRODID
}

TABLE FEATURES {
  ID PRIMARY KEY AUTO INCREMENT NOT NULL
  NAME VARCHAR(100)
  VALUE VARCHAR(100)
}

TABLE SKUS {
  SKUID PRIMARY KEY NOT NULL
  QUANTITY INT
  SIZE VARCHAR(2)
  PRODID
}

TABLE PHOTOS {
  PHOTOID NOT NULL PRIMARY KEY INT
  THUMBNAILURL LONGTEXT
  URL LONGTEXT
  STYLEID
}